[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 2

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 3

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 4

# Social Media Configuration

[[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/akkonomi"
    weight = 1

[[social]]
    identifier = "dev"
    name = "DEV"
    url = "https://dev.to/4k1k0"
    weight = 2

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/4k1k0"
    weight = 3

[[social]]
    identifier = "linkedin"
    name = "Linkedin"
    url = "https://www.linkedin.com/in/rodrigo-patino-dev/"
    weight = 4
